### ISSUE TITLE
3-style手順表の書式

### ISSUE THREAD

**Issue by kits** [sakabar/hinemos#577]
セットアップの記号として : を使えるようにしてほしいです。
例えば [A: [B, C]] を A B C B' C' A' の意味で書きたいのですが、
現状だと [A, [B, C]] のように書くしかなく、
これは厳密には A B C B' C' A' C B C' B' の意味となります。
参考: https://www.speedsolving.com/wiki/index.php/Commutators_and_Conjugates

また、コミュテータでない単なる手順も [ ] なしでそのまま書けると有難いです。

**Comment by sakabar** [comment]
@kits ご要望ありがとうございます。

1点目
セットアップの記号は、私の理解不足でした。 誰かの手順表でセットアップが `,` で書かれていたように思っていたのですが、今見たらどうやら勘違いのようです。
`:`も受け入れるように修正します。

2点目
どこにも書いていないのですが、コミュテータでない単なる手順も以下の2つの方法で登録できます。
例として、DF-LU-RU `M U' M U2 M' U' M'` で説明します。

(A) 「3-style手順表」で`[M U' M U2 M' U' M']`と書く
(B) 「3-style登録」で「セットアップ」に`M U' M U2 M' U' M'`、手順1と手順2を空欄にして「登録」

隠れ仕様になっているのはマズいので、3-style登録ページかどこかに追記します。

**Comment by kits** [comment]
返信ありがとうございます!

2点目については、保存する際のアラートでそのように書けば登録できるのは分かったのですが、手順表で角括弧を付けずに `M U' M U2 M' U' M'` とそのまま書けるようにしたい、という要望となります。
角括弧はあくまでコミュテータ `[A, B]` または共役 `[A: B]` のための記号であり、`,` や `:` の無い `[A B]` という記法はどこにも定義されていないと思いますので…。(コミュテータ等でない単なる手順であることの明確化にもなると思います)
面倒かとは思いますが、考慮頂ければ幸いです。

`:` が書けるのはとてもありがたいです! よろしくお願いします。

**Comment by kits** [comment]
たびたびすみません、`:` についてですが、単に「入力を受け入れる」というのではなく、手順表でも `:` は `:` として表示されるようになると有難いです。
例えば DF LB DB を `L U` セットアップ + `M2 U2 M' U2 M'` とする場合、手順表で `[L U: M2 U2 M' U2 M']` と書きたい(表示されるようにしたい)のですが、これが `[L U, M2 U2 M' U2 M']` になると意味が変わってしまうので。

**Comment by sakabar** [comment]
> 手順表で角括弧を付けずに M U' M U2 M' U' M' とそのまま書けるようにしたい
これは可能だと思います

> 手順表でも : は : として表示されるようになると有難いです。
これも可能だと思います

> [L U: M2 U2 M' U2 M']
`:`表記以前に、このような「セットアップ + ただの手順」は今の仕様ではできない作りだった気がするので、一番手間のかかる部分です。

要望としては承知しましたが、もしマズい設計だとちょっと直せるか保証はできません、すみません。

**Comment by sakabar** [comment]
@kits 以下の2点については実現できましたのでリリースします。
> 手順表で角括弧を付けずに M U' M U2 M' U' M' とそのまま書けるようにしたい
> 手順表でも : は : として表示されるようになると有難いです。

一方、 `[A: B] = A B A'` 型は対応できていません。
初期の設計思想で`:;,、`などを同一視して扱っていたため、`[A, B]`型と`[A: B]`型を同一視するようなコードになっていまして、申し訳ありませんが直せそうにありません。

**Comment by sakabar** [comment]
メモ
https://github.com/sakabar/hinemos/issues/241

**Comment by kits** [comment]
了解しました。ご対応有難うございます!
